export const supplyGroups = [
  {
    id: 'race-kit',
    label: 'race kit',
    items: [
      { id: 'running-vest', label: 'running vest' },
      { id: 'soft-flasks', label: 'soft flasks', detail: '2' },
      { id: 'extra-flasks', label: 'extra flask bottles' },
      { id: 'collapsible-cup', label: 'collapsible cup' },
      { id: 'trekking-poles', label: 'trekking poles' },
      { id: 'headlamp', label: 'headlamp' },
      { id: 'backup-headlamp', label: 'backup headlamp' },
      { id: 'headlamp-batteries', label: 'headlamp batteries' },
      { id: 'phone', label: 'phone' },
      { id: 'garmin-watch', label: 'Garmin watch' },
      { id: 'emergency-blanket', label: 'emergency blanket' },
      { id: 'small-trash-bags', label: 'small trash bags' },
    ],
  },
  {
    id: 'clothing',
    label: 'clothing & drop bags',
    items: [
      { id: 'jacket', label: 'jacket / rain shell' },
      { id: 'warm-layer', label: 'warm layer' },
      { id: 'extra-shorts', label: 'extra shorts' },
      { id: 'extra-tank', label: 'extra tank' },
      { id: 'extra-t-shirt', label: 'extra T-shirt' },
      { id: 'extra-hat', label: 'extra hat' },
      { id: 'spare-socks', label: 'spare socks', detail: '2 pairs' },
      { id: 'extra-shoes', label: 'extra pair of shoes' },
      { id: 'gloves', label: 'gloves' },
      { id: 'buff', label: 'buff / neck gaiter' },
    ],
  },
  {
    id: 'care',
    label: 'body & foot care',
    items: [
      { id: 'body-glide', label: 'body glide' },
      { id: 'kt-tape', label: 'KT tape' },
      { id: 'blister-kit', label: 'blister kit' },
      { id: 'sunscreen', label: 'sunscreen' },
      { id: 'lip-balm', label: 'lip balm' },
      { id: 'face-wipes', label: 'face wipes' },
      { id: 'hand-towel', label: 'hand towel' },
      { id: 'toilet-paper', label: 'toilet paper' },
      { id: 'contact-lenses', label: 'extra contact lenses' },
      { id: 'eye-drops', label: 'eye drops' },
      { id: 'antacid', label: 'antacid' },
      { id: 'acetaminophen', label: 'Tylenol / acetaminophen' },
      { id: 'personal-medication', label: 'personal medication' },
      { id: 'toothbrush', label: 'toothbrush' },
      { id: 'toothpaste', label: 'toothpaste' },
    ],
  },
  {
    id: 'nutrition',
    label: 'nutrition & hydration',
    items: [
      { id: 'water', label: 'water' },
      { id: 'sparkling-water', label: 'sparkling water', detail: 'crew / finish' },
      { id: 'redbull', label: 'Red Bull' },
      { id: 'gels-chews', label: 'gels / chews' },
      { id: 'salty-snacks', label: 'salty snacks' },
      { id: 'real-food', label: 'real food' },
      { id: 'ginger-candy', label: 'ginger candy' },
      { id: 'caffeine', label: 'caffeine' },
    ],
  },
  {
    id: 'power-logistics',
    label: 'power & logistics',
    items: [
      { id: 'external-battery', label: 'external battery' },
      { id: 'phone-charger', label: 'phone charger' },
      { id: 'garmin-charger', label: 'Garmin charger' },
      { id: 'charging-cables', label: 'charging cables' },
      { id: 'wallet-id', label: 'wallet / ID' },
      { id: 'crew-instructions', label: 'crew instructions' },
      { id: 'labeled-drop-bags', label: 'labeled drop bags' },
      { id: 'cooler-ice', label: 'cooler / ice' },
    ],
  },
  {
    id: 'recovery',
    label: 'recovery',
    items: [
      { id: 'compression-socks', label: 'compression socks' },
      { id: 'massage-ball', label: 'massage ball' },
      { id: 'theragun', label: 'Theragun' },
      { id: 'hand-roller', label: 'hand roller' },
      { id: 'foam-roller', label: 'foam roller' },
    ],
  },
]
